- name: Setup CentOS7
  hosts: all
  remote_user: centos
  become: yes
  become_method: sudo
  tasks:
        - name: set enforce 0
          command: setenforce 0

        - name: SELinux permissive
          replace:
            dest: /etc/selinux/config
            regexp: "^SELINUX=enforcing$"
            replace: "SELINUX=permissive"

        - name: update
          yum: name=* state=latest

        - name: install repo
          yum: name={{ item }} 
          with_items:
            - epel-release
            - centos-release-scl-rh
            - centos-release-scl
            - http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
            - http://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-release-3.2-1.el7.noarch.rpm
            - python-pip

        - name: tools install
          yum: name={{ item }} state=installed
          with_items:
            - vim-enhanced
            - wget
            - unzip
            - zabbix-agent

        - name: pexpect install
          pip: name=pexpect state=present

        - name: zabbix-agent setup
          replace:
            dest: /etc/zabbix/zabbix_agentd.conf
            regexp: "^Server=127.0.0.1$"
            replace: "Server=10.0.0.11"

        - name: zabbix-agent setup2
          replace:
            dest: /etc/zabbix/zabbix_agentd.conf
            regexp: "^ServerActive=127.0.0.1$"
            replace: "ServerActive=10.0.0.11"

        - name: zabbix-agent setup3
          replace:
            dest: /etc/zabbix/zabbix_agentd.conf
            regexp: "^Hostname=Zabbix server$"
            replace: "#Hostname=Zabbix server$"

        - name: zabbix-agent setup4
          replace:
            dest: /etc/zabbix/zabbix_agentd.conf
            regexp: "^# HostnameItem=system.hostname$"
            replace: "HostnameItem=system.hostname$"
